openapi: 3.0.3
info:
  title: AstraCore Billing Service API
  description: API for managing Invoices, Orders, and Billing operations.
  version: 1.0.0
  contact:
    name: AstraCore Team
    email: support@astracore.com

servers:
  - url: http://localhost:8081
    description: Local Development Server

paths:
  /api/v1/invoices:
    get:
      summary: List Invoices
      description: Retrieve a paginated list of invoices.
      operationId: listInvoices
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/InvoiceDTO'
                  totalElements:
                    type: integer
                  totalPages:
                    type: integer

    post:
      summary: Create Invoice
      description: Create a new invoice.
      operationId: createInvoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceCreateDTO'
      responses:
        '201':
          description: Invoice created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDTO'
        '400':
          description: Invalid input

  /api/v1/invoices/{invoiceId}:
    get:
      summary: Get Invoice
      description: Retrieve a specific invoice by ID.
      operationId: getInvoice
      parameters:
        - name: invoiceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDTO'
        '404':
          description: Invoice not found

    put:
      summary: Update Invoice
      description: Update an existing invoice (only if in draft status).
      operationId: updateInvoice
      parameters:
        - name: invoiceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceCreateDTO'
      responses:
        '200':
          description: Invoice updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceDTO'
        '400':
          description: Invalid input or status

  /api/v1/invoices/{invoiceId}/approve:
    post:
      summary: Approve Invoice
      description: Transition invoice status to APPROVED.
      operationId: approveInvoice
      parameters:
        - name: invoiceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Invoice approved
        '400':
          description: Invalid transition

  /api/v1/invoices/{invoiceId}/cancel:
    post:
      summary: Cancel Invoice
      description: Transition invoice status to CANCELLED.
      operationId: cancelInvoice
      parameters:
        - name: invoiceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Invoice cancelled
        '400':
          description: Invalid transition

  /api/v1/orders:
    post:
      summary: Create Sales Order
      description: Create a new sales order.
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateDTO'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDTO'

  /api/v1/payments:
    post:
      summary: Receive Payment
      description: Record a payment against an invoice.
      operationId: receivePayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentCreateDTO'
      responses:
        '201':
          description: Payment recorded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDTO'

components:
  schemas:
    InvoiceDTO:
      type: object
      properties:
        invoiceId:
          type: string
          format: uuid
        invoiceTypeId:
          type: string
          example: SALES_INVOICE
        partyIdFrom:
          type: string
          format: uuid
        partyIdTo:
          type: string
          format: uuid
        invoiceDate:
          type: string
          format: date
        dueDate:
          type: string
          format: date
        statusId:
          type: string
          example: IN_PROCESS
        currencyUomId:
          type: string
          example: USD
        totalAmount:
          $ref: '#/components/schemas/MoneyDTO'
        lines:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLineDTO'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    InvoiceCreateDTO:
      type: object
      required:
        - invoiceTypeId
        - partyIdFrom
        - partyIdTo
        - invoiceDate
        - currencyUomId
      properties:
        invoiceTypeId:
          type: string
          example: SALES_INVOICE
        partyIdFrom:
          type: string
          format: uuid
        partyIdTo:
          type: string
          format: uuid
        invoiceDate:
          type: string
          format: date
        dueDate:
          type: string
          format: date
        currencyUomId:
          type: string
          example: USD
        lines:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLineCreateDTO'

    InvoiceLineDTO:
      type: object
      properties:
        invoiceLineId:
          type: string
          format: uuid
        invoiceItemSeqId:
          type: integer
        productId:
          type: string
          format: uuid
        description:
          type: string
        quantity:
          type: number
        amount:
          $ref: '#/components/schemas/MoneyDTO'

    InvoiceLineCreateDTO:
      type: object
      required:
        - invoiceItemSeqId
        - amount
      properties:
        invoiceItemSeqId:
          type: integer
        productId:
          type: string
          format: uuid
        description:
          type: string
        quantity:
          type: number
        amount:
          type: number

    MoneyDTO:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string

    OrderDTO:
      type: object
      properties:
        orderId:
          type: string
          format: uuid
        orderName:
          type: string
        orderDate:
          type: string
          format: date-time
        partyId:
          type: string
          format: uuid
        grandTotal:
          $ref: '#/components/schemas/MoneyDTO'
        statusId:
          type: string

    OrderCreateDTO:
      type: object
      required:
        - partyId
        - orderDate
      properties:
        orderName:
          type: string
        orderDate:
          type: string
          format: date-time
        partyId:
          type: string
          format: uuid

    PaymentDTO:
      type: object
      properties:
        paymentId:
          type: string
          format: uuid
        invoiceId:
          type: string
          format: uuid
        amount:
          $ref: '#/components/schemas/MoneyDTO'
        paymentMethodId:
          type: string
        paymentDate:
          type: string
          format: date-time

    PaymentCreateDTO:
      type: object
      required:
        - invoiceId
        - amount
        - paymentMethodId
      properties:
        invoiceId:
          type: string
          format: uuid
        amount:
          $ref: '#/components/schemas/MoneyDTO'
        paymentMethodId:
          type: string
          example: CREDIT_CARD
